### ISSUE TITLE
orders in Customer will be a List of Customerorders

### ISSUE THREAD

**Issue by 22shubh22** [22shubh22/shopAt#21]
- customerorder will be a new collection 
Add Customerorder model.

Contumerorder models included
* id
* date and time of order
* List of product in order
* Payment done - Yes/No
* Delivery date and time
* State - pending/complete

**Comment by 22shubh22** [comment]
@RajaVamsi11 do you agree with it?
this is not implemented, right?

**Comment by srihariash999** [comment]
#33  done with this.
