### ISSUE TITLE
Handle incorrect Phone and incorrect OTP

### ISSUE THREAD

**Issue by 22shubh22** [22shubh22/shopAt#3]
Currently no error is shown if phone number is incorrect. 
There should be some sort of error displayed when smsCode is not generated from the firebase

Same should happen when OTP is incorrect.

**Comment by 22shubh22** [comment]
@RajaVamsi11 I can tell you the flow of authentication if you want.

**Comment by RajaVamsi11** [comment]
Yes @22shubh22, Please explain. I will fix the login flow first.
